### ISSUE TITLE
TypeError: OAuth2Strategy requires a clientID option

### ISSUE THREAD

**Issue by 4ossiblellc** [mjhea0/passport-examples#5]
It seems the Google Strategy requires to have a clientID option.

```
/Users/someone/development/nurtureNetworks/passport-examples/node_modules/passport-google-oauth2/node_modules/passport-oauth2/lib/strategy.js:83
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clie
                                 ^
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/Users/someone/development/nurtureNetworks/passport-examples/node_modules/passport-google-oauth2/node_modules/passport-oauth2/lib/strategy.js:83:34)
    at new Strategy (/Users/someone/development/nurtureNetworks/passport-examples/node_modules/passport-google-oauth2/lib/oauth2.js:48:18)
    at Object.<anonymous> (/Users/someone/development/nurtureNetworks/passport-examples/authentication.js:103:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/someone/development/nurtureNetworks/passport-examples/app.js:10:14)
```

**Comment by 4ossiblellc** [comment]
Please change the README file to:

```
     google: {
-      consumerKey: 'get_your_own',
-      consumerSecret: 'get_your_own',
+      clientID: 'get_your_own',
+      clientSecret: 'get_your_own',
       callbackURL: 'http://127.0.0.1:1337/auth/google/callback'
     },
```

**Comment by mjhea0** [comment]
https://github.com/mjhea0/passport-examples/pull/9
